#ifndef CMAKE_TEMPLATE_VERSION_HPP
#define CMAKE_TEMPLATE_VERSION_HPP

#define CMAKE_TEMPLATE_VERSION_MAJOR 0
#define CMAKE_TEMPLATE_VERSION_MINOR 0
#define CMAKE_TEMPLATE_VERSION_PATCH 1

#define CMAKE_TEMPLATE_TO_VERSION(major, minor, patch) \
  ((major) * 10000 + (minor) * 100 + (patch))
#define CMAKE_TEMPLATE_VERSION                            \
  CMAKE_TEMPLATE_TO_VERSION(CMAKE_TEMPLATE_VERSION_MAJOR, \
                            CMAKE_TEMPLATE_VERSION_MINOR, \
                            CMAKE_TEMPLATE_VERSION_PATCH)

#endif  // CMAKE_TEMPLATE_VERSION_HPP