name: Android

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  android:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - android-29
          - android-33
        abi:
          - arm64-v8a
        build_type: [Debug, Release]
    runs-on: ubuntu-24.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt -qq update
          sudo apt -qq install -y ninja-build --no-install-recommends --no-install-suggests

      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -S $GITHUB_WORKSPACE -B build \
          -GNinja \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=${{ matrix.platform }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build project
        run: cmake --build build/