name: clang-tidy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: sudo apt-get update -yq

    - run: sudo apt-get install -yq clang-tidy

    - run: find src/ include/ -type f \( -name "*.cpp" -o -name "*.hpp" \) | xargs -I '{}' clang-tidy --quiet '{}' -- --std=c++23 -Iinclude