name: Linux

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  linux-build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-24.04
            compiler: g++
          - os: ubuntu-24.04
            compiler: clang++
          - os: ubuntu-latest
            compiler: g++
          - os: ubuntu-latest
            compiler: clang++
        build_type: [Release, Debug]
    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Install Dependencies
        run: |
          sudo apt -qq update
          sudo apt -qq install -y ninja-build --no-install-recommends --no-install-suggests

      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -S $GITHUB_WORKSPACE -B build \
          -GNinja \
          -DCMAKE_CXX_COMPILER=${{ matrix.platform.compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build project
        run: cmake --build build/

      - name: Run tests
        working-directory: build/
        run: ctest -C ${{ matrix.build_type }} --output-on-failure